set(_CATKIN_CURRENT_PACKAGE "pluginlib_tutorials_")
set(pluginlib_tutorials__VERSION "0.0.0")
set(pluginlib_tutorials__MAINTAINER "yanqiao <yanqiao@todo.todo>")
set(pluginlib_tutorials__PACKAGE_FORMAT "1")
set(pluginlib_tutorials__BUILD_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials__BUILD_EXPORT_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials__BUILDTOOL_DEPENDS "catkin")
set(pluginlib_tutorials__BUILDTOOL_EXPORT_DEPENDS )
set(pluginlib_tutorials__EXEC_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials__RUN_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials__TEST_DEPENDS )
set(pluginlib_tutorials__DOC_DEPENDS )
set(pluginlib_tutorials__DEPRECATED "")