# CMake generated Testfile for 
# Source directory: /mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials
# Build directory: /mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/ros_tutorials/rospy_tutorials
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_rospy_tutorials_rostest_test_test-add-two-ints.launch "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results/rospy_tutorials/rostest-test_test-add-two-ints.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-add-two-ints.xml --results-base-dir \"/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results\" /mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-add-two-ints.launch ")
ADD_TEST(_ctest_rospy_tutorials_rostest_test_test-peer-subscribe-notify.launch "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results/rospy_tutorials/rostest-test_test-peer-subscribe-notify.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-peer-subscribe-notify.xml --results-base-dir \"/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results\" /mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-peer-subscribe-notify.launch ")
ADD_TEST(_ctest_rospy_tutorials_rostest_test_test-add-two-ints-with-roscpp-server.launch "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results/rospy_tutorials/rostest-test_test-add-two-ints-with-roscpp-server.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-add-two-ints-with-roscpp-server.xml --results-base-dir \"/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results\" /mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-add-two-ints-with-roscpp-server.launch ")
ADD_TEST(_ctest_rospy_tutorials_rostest_test_test-talker-listener.launch "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results/rospy_tutorials/rostest-test_test-talker-listener.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-talker-listener.xml --results-base-dir \"/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results\" /mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-talker-listener.launch ")
ADD_TEST(_ctest_rospy_tutorials_rostest_test_test-talker-listener-with-roscpp.launch "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results/rospy_tutorials/rostest-test_test-talker-listener-with-roscpp.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-talker-listener-with-roscpp.xml --results-base-dir \"/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results\" /mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-talker-listener-with-roscpp.launch ")
ADD_TEST(_ctest_rospy_tutorials_rostest_test_test-on-shutdown.launch "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results/rospy_tutorials/rostest-test_test-on-shutdown.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-on-shutdown.xml --results-base-dir \"/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results\" /mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-on-shutdown.launch ")
ADD_TEST(_ctest_rospy_tutorials_rostest_test_test-connection-header.launch "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results/rospy_tutorials/rostest-test_test-connection-header.xml" "--return-code" "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-connection-header.xml --results-base-dir \"/mnt/data/work/ssh_test/ros_beginner/catkin_ws/build-src-Desktop_Qt_5_6_0_GCC_64bit-Debug/test_results\" /mnt/data/work/ssh_test/ros_beginner/catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-connection-header.launch ")
