set(_CATKIN_CURRENT_PACKAGE "kobuki_controller_tutorial")
set(kobuki_controller_tutorial_VERSION "0.0.0")
set(kobuki_controller_tutorial_MAINTAINER "yanqiao <yanqiao@todo.todo>")
set(kobuki_controller_tutorial_PACKAGE_FORMAT "1")
set(kobuki_controller_tutorial_BUILD_DEPENDS "kobuki_msgs" "nodelet" "roscpp" "std_msgs" "yocs_controllers")
set(kobuki_controller_tutorial_BUILD_EXPORT_DEPENDS "kobuki_msgs" "nodelet" "roscpp" "std_msgs" "yocs_controllers")
set(kobuki_controller_tutorial_BUILDTOOL_DEPENDS "catkin")
set(kobuki_controller_tutorial_BUILDTOOL_EXPORT_DEPENDS )
set(kobuki_controller_tutorial_EXEC_DEPENDS "kobuki_msgs" "nodelet" "roscpp" "std_msgs" "yocs_controllers")
set(kobuki_controller_tutorial_RUN_DEPENDS "kobuki_msgs" "nodelet" "roscpp" "std_msgs" "yocs_controllers")
set(kobuki_controller_tutorial_TEST_DEPENDS )
set(kobuki_controller_tutorial_DOC_DEPENDS )
set(kobuki_controller_tutorial_DEPRECATED "")