set(_CATKIN_CURRENT_PACKAGE "pluginlib_tutorials_2")
set(pluginlib_tutorials_2_VERSION "0.0.0")
set(pluginlib_tutorials_2_MAINTAINER "yanqiao <yanqiao@todo.todo>")
set(pluginlib_tutorials_2_PACKAGE_FORMAT "1")
set(pluginlib_tutorials_2_BUILD_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials_2_BUILD_EXPORT_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials_2_BUILDTOOL_DEPENDS "catkin")
set(pluginlib_tutorials_2_BUILDTOOL_EXPORT_DEPENDS )
set(pluginlib_tutorials_2_EXEC_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials_2_RUN_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials_2_TEST_DEPENDS )
set(pluginlib_tutorials_2_DOC_DEPENDS )
set(pluginlib_tutorials_2_DEPRECATED "")