set(_CATKIN_CURRENT_PACKAGE "boot_node")
set(boot_node_VERSION "0.0.0")
set(boot_node_MAINTAINER "yanqiao <yanqiao@todo.todo>")
set(boot_node_PACKAGE_FORMAT "1")
set(boot_node_BUILD_DEPENDS "roscpp" "rospy")
set(boot_node_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(boot_node_BUILDTOOL_DEPENDS "catkin")
set(boot_node_BUILDTOOL_EXPORT_DEPENDS )
set(boot_node_EXEC_DEPENDS "roscpp" "rospy")
set(boot_node_RUN_DEPENDS "roscpp" "rospy")
set(boot_node_TEST_DEPENDS )
set(boot_node_DOC_DEPENDS )
set(boot_node_DEPRECATED "")